monolog:
    channels:
        - webhook
        - deprecation
        - nutgram

    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            channels: ['!deprecation']
            buffer_size: 50
        nested:
            type: stream
            path: '%kernel.logs_dir%/error.log'
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
        deprecation:
            type: stream
            channels: [deprecation]
            path: php://stderr
            formatter: monolog.formatter.json
        webhook:
            type: stream
            channels: [webhook]
            path: '%kernel.logs_dir%/webhook.log'
            formatter: monolog.formatter.json
        nutgram:
            type: stream
            channels: [nutgram]
            path: '%kernel.logs_dir%/nutgram.log'
#            formatter: monolog.formatter.json
